feat: create start and photo screens
alexlatypov94/native-app pull request #1
Opened 2021-08-13 09:41 UTC by alexlatypov94

2021-08-13 10:18 UTC, bezvod008 requested changes

2021-08-13 10:18 UTC, bezvod008 commented on app/App.tsx
> +            <Stack.Screen name="Start" component={StartScreen} />
Имена роутов лучше вынести в константы

`const RootRoutes = {
   start: "Start"
   // ...
}`

2021-08-13 10:18 UTC, bezvod008 commented on app/components/Main/PhotoScreen/PhotoScreen.tsx
> +  const renderPic = (isOdd: boolean) => {
Используй FlatList для рендера массивов

2021-08-13 10:18 UTC, bezvod008 commented on app/components/Main/PhotoScreen/PhotoScreen.tsx
> +  const [isLoading, setIsLoading] = useState<boolean>(false);
`isLoading` не используется

2021-08-13 10:18 UTC, bezvod008 commented on app/components/Main/StartScreen/StartScreen.tsx
> +export const StartScreen: React.FC<INavProps> = ({navigation}) => {
Думаю, что лучше использовать хук `useNavigation`, вместо того чтобы пробрасывать его в скрин

2021-08-13 10:18 UTC, bezvod008 commented on app/components/Main/StartScreen/StartScreen.tsx
> +      <TouchableWithoutFeedback onPress={() => navigation.navigate('Photos')}>
Вот эту инлайн функцию лучше вынести

2021-08-13 10:47 UTC, alexlatypov94 commented on app/App.tsx
> +            <Stack.Screen name="Start" component={StartScreen} />
done

2021-08-13 11:04 UTC, alexlatypov94 commented on app/components/Main/StartScreen/StartScreen.tsx
> +export const StartScreen: React.FC<INavProps> = ({navigation}) => {
done

2021-08-13 11:05 UTC, alexlatypov94 commented on app/components/Main/StartScreen/StartScreen.tsx
> +      <TouchableWithoutFeedback onPress={() => navigation.navigate('Photos')}>
done

2021-08-13 11:16 UTC, alexlatypov94 commented on app/components/Main/PhotoScreen/PhotoScreen.tsx
> +  const [isLoading, setIsLoading] = useState<boolean>(false);
done

2021-08-13 12:07 UTC, alexlatypov94 commented on app/components/Main/PhotoScreen/PhotoScreen.tsx
> +  const renderPic = (isOdd: boolean) => {
done

2021-08-16 11:57 UTC, bezvod008 requested changes

2021-08-16 11:57 UTC, bezvod008 commented on app/components/Main/PhotoScreen/PhotoScreen.tsx
> +  const renderPic = () => {
Это зачем?)  Почему бы просто JSX, который возвращает эта функция не использовать?

2021-08-16 11:57 UTC, bezvod008 commented on app/components/Main/PhotoScreen/PhotoScreen.tsx
> +  const image = ({item, index}: any) => {
Эту функцию можно вынести за компонент, для того, чтобы избежать её пересоздания на каждый ре-рендер

2021-08-19 05:53 UTC, alexlatypov94 commented on app/components/Main/PhotoScreen/PhotoScreen.tsx
> +  const image = ({item, index}: any) => {
done

2021-08-19 05:53 UTC, alexlatypov94 commented on app/components/Main/PhotoScreen/PhotoScreen.tsx
> +  const renderPic = () => {
done

2021-08-19 06:18 UTC, merged