Database
alexlatypov94/native-app pull request #8
Opened 2021-08-31 08:40 UTC by alexlatypov94

2021-09-01 13:36 UTC, bezvod008 requested changes

2021-09-01 13:36 UTC, bezvod008 commented on app/store/action/photosAction.ts
> +    type: PhotosActionTypes.GET_REFRESH_REQUEST,
Это нормально, что у тебя 10 экшнов с одним и тем же `type`?

2021-09-01 13:36 UTC, bezvod008 commented on app/components/RootStack/Main/SelectedPhoto/SelectedPhoto.tsx
> +    getPhotoFromDatabase(id).then(res => setPhotoDB(res?.photoData));
У тебя же `redux-saga` для эффектов

2021-09-01 13:36 UTC, bezvod008 commented on app/components/RootStack/Main/SelectedPhoto/SelectedPhoto.tsx
> +  const isLiked = isConnected
Говорили об этом моменте, лучше данные из стора забирать и обновлять его новыми данными

2021-09-01 13:36 UTC, bezvod008 commented on app/components/AppRoot.tsx
> +        firestore()
Это нужно вынести в сагу

2021-09-01 14:28 UTC, merged

2021-09-01 15:01 UTC, alexlatypov94 commented on app/store/action/photosAction.ts
> +    type: PhotosActionTypes.GET_REFRESH_REQUEST,
done

2021-09-02 09:37 UTC, alexlatypov94 commented on app/components/AppRoot.tsx
> +        firestore()
done

2021-09-02 11:32 UTC, alexlatypov94 commented on app/components/RootStack/Main/SelectedPhoto/SelectedPhoto.tsx
> +  const isLiked = isConnected
done

2021-09-02 11:32 UTC, alexlatypov94 commented on app/components/RootStack/Main/SelectedPhoto/SelectedPhoto.tsx
> +    getPhotoFromDatabase(id).then(res => setPhotoDB(res?.photoData));
done